<a href="https://colab.research.google.com/github/ieshita/Simple-Linear-Regression/blob/main/Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving FuelConsumption.csv to FuelConsumption.csv
User uploaded file "FuelConsumption.csv" with length 72629 bytes


In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/FuelConsumption.csv")

In [ ]:
df

MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4   
1          2014  ACURA         ILX         COMPACT         2.4          4   
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4   
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6   
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6   
...         ...    ...         ...             ...         ...        ...   
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6   
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6   
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6   
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6   
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6   

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7   
1              M6        Z                  11.2                  7.7   
2             AV7        Z                   6.0                  5.8   
3             AS6        Z                  12.7                  9.1   
4             AS6        Z                  12.1                  8.7   
...           ...      ...                   ...                  ...   
1062          AS6        X                  13.4                  9.8   
1063          AS6        X                  13.2                  9.5   
1064          AS6        X                  13.4                  9.8   
1065          AS6        X                  12.9                  9.3   
1066          AS6        X                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                      8.5                        33           196  
1                      9.6                        29           221  
2                      5.9                        48           136  
3                     11.1                        25           255  
4                     10.6                        27           244  
...                    ...                       ...           ...  
1062                  11.8                        24           271  
1063                  11.5                        25           264  
1064                  11.8                        24           271  
1065                  11.3                        25           260  
1066                  12.8                        22           294  

[1067 rows x 13 columns]

In [ ]:
df.isnull().sum()

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

In [ ]:
x=df[['ENGINESIZE']].values

In [ ]:
y=df['CO2EMISSIONS'].values

In [ ]:
x

array([[2. ],
       [2.4],
       [1.5],
       ...,
       [3. ],
       [3.2],
       [3.2]])

In [ ]:
y

array([196, 221, 136, ..., 271, 260, 294])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=1)

In [ ]:
x_test

array([[3. ],
       [1.4],
       [2. ],
       [2. ],
       [4.6],
       [3. ],
       [2. ],
       [1.8],
       [3. ],
       [2.4],
       [2.4],
       [3. ],
       [2.4],
       [5.2],
       [2.5],
       [2.5],
       [1.6],
       [4.4],
       [3.5],
       [2.4],
       [6. ],
       [2.5],
       [3.7],
       [3.5],
       [3.7],
       [3. ],
       [1.2],
       [5.5],
       [1.6],
       [2. ],
       [3. ],
       [5.2],
       [3.5],
       [5.3],
       [4. ],
       [5.3],
       [6.2],
       [1.5],
       [4.2],
       [3.3],
       [3. ],
       [6.3],
       [2. ],
       [3.6],
       [3.7],
       [2. ],
       [1.4],
       [1.4],
       [2. ],
       [3.4],
       [1.6],
       [5.7],
       [4.3],
       [6.2],
       [2. ],
       [3.7],
       [2.5],
       [5. ],
       [3.7],
       [1.6],
       [2.4],
       [2.7],
       [2. ],
       [2. ],
       [2. ],
       [1.8],
       [3.7],
       [3.6],
       [2. ],
       [1.6],
       [2. ],
      

In [ ]:
y_test

array([274, 200, 196, 161, 320, 224, 192, 189, 221, 182, 230, 283, 189,
       400, 186, 168, 196, 338, 271, 225, 413, 223, 248, 264, 308, 232,
       147, 246, 179, 274, 246, 409, 235, 294, 281, 317, 377, 168, 407,
       267, 232, 361, 235, 258, 253, 202, 191, 124, 181, 246, 184, 354,
       285, 361, 225, 283, 205, 262, 269, 175, 209, 271, 221, 186, 235,
       189, 260, 248, 209, 232, 225, 225, 254, 232, 290, 294, 145, 276,
       209, 267, 340, 179, 294, 347, 225, 382, 246, 251, 212, 237, 380,
       292, 192, 242, 225, 209, 380, 393, 242, 288, 216, 338, 165, 278,
       218, 292, 184, 294, 200, 209, 235, 402, 419, 317, 294, 253, 207,
       223, 338, 196, 248, 290, 207, 267, 179, 218, 313, 340, 354, 202,
       216, 179, 271, 285, 344, 350, 342, 198, 299, 246, 182, 221, 212,
       159, 264, 212, 315, 396, 317, 276, 207, 267, 359, 380, 202, 198,
       224, 324, 189, 193, 161, 235, 297, 173, 285, 308, 267, 255, 301,
       209, 288, 278, 297, 184, 343, 324, 322, 253, 136, 413, 32

In [ ]:
reg=LinearRegression()

In [ ]:
reg.fit(x_train, y_train)

LinearRegression()

In [ ]:
reg.predict(x_test)

array([243.34753384, 180.59365156, 204.12635741, 204.12635741,
       306.10141612, 243.34753384, 204.12635741, 196.28212213,
       243.34753384, 219.81482799, 219.81482799, 243.34753384,
       219.81482799, 329.63412198, 223.73694563, 223.73694563,
       188.43788684, 298.25718084, 262.95812205, 219.81482799,
       361.01106312, 223.73694563, 270.80235734, 262.95812205,
       270.80235734, 243.34753384, 172.74941627, 341.40047491,
       188.43788684, 204.12635741, 243.34753384, 329.63412198,
       262.95812205, 333.55623962, 282.56871027, 333.55623962,
       368.85529841, 184.5157692 , 290.41294555, 255.11388677,
       243.34753384, 372.77741605, 204.12635741, 266.8802397 ,
       270.80235734, 204.12635741, 180.59365156, 180.59365156,
       204.12635741, 259.03600441, 188.43788684, 349.24471019,
       294.3350632 , 368.85529841, 204.12635741, 270.80235734,
       223.73694563, 321.78988669, 270.80235734, 188.43788684,
       219.81482799, 231.58118091, 204.12635741, 204.12

In [ ]:
reg.intercept_

125.68400456178537

In [ ]:
reg.coef_

array([39.22117643])

In [ ]:
reg.score(x_test,y_test)

0.7672977379444554